apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector: # How to select pods belonging to this deployment. Must match the pod template's labels
    matchLabels:
      app: frontend # List of labels
  template: # This is the pod template, paste in the pod spec from frontend-pod.yaml
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - image: ghcr.io/liemqle/liemsniffers-fortune-cookies/frontend:latest
          imagePullPolicy: Always
          name: fc-frontend
          ports:
            - containerPort: 8080
          env:
            - name: BACKEND_PORT
              value: "9000"
            - name: BACKEND_DNS
              value: backend
          resources: {}
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: frontend
  ports:
  - port: 8080
    targetPort: 8080
  type: NodePort
