services:
  frontend:
    build: ./frontend
    environment:
      - BACKEND_PORT=9000
      - BACKEND_DNS=backend
    depends_on: 
      - backend
    networks:
      - fortune-cookie-frontend

  backend:
    build: ./backend
    depends_on:
      - redis
    environment:
      - REDIS_DNS=redis

    networks:
      - fortune-cookie-frontend
      - fortune-cookie-backend

  redis:
    image: redis:8.2
    networks:
      - fortune-cookie-backend

networks:
  fortune-cookie-frontend:
  fortune-cookie-backend:
  
