apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 1
  selector: # How to select pods belonging to this deployment. Must match the pod template's labels
    matchLabels:
      app: backend # List of labels
  template: # This is the pod template, paste in the pod spec from backend-pod.yaml
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - image: ghcr.io/liemqle/liemsniffers-fortune-cookies/backend:latest
          name: fc-backend
          ports:
          - containerPort: 9000
          env:
            - name: REDIS_DNS
              value: redis
          resources: {}
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: backend
  name: backend
spec:
  selector:
    app: backend
  ports:
  - port: 9000
    protocol: TCP
    targetPort: 9000
  type: ClusterIP