name: Liemsniffers CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  PreTestingFrontend:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0
      - name: Install Go
        uses: actions/setup-go@v5.5.0
      - name: Run Test
        run: cd frontend && go test
