name: Liemsniffers CI 
env:
  GIT_COMMIT: ${{ github.sha }}
  GIT_REPO: ${{ github.event.repository.name }}
  DOCKER_REPO: "ghcr.io"
  DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  PreTestingFrontend:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0
      - name: Install Go
        uses: actions/setup-go@v5.5.0
      - name: Run Test
        run: cd frontend && go test
  
  Containerize:
    runs-on: ubuntu-24.04
    needs: [PreTestingFrontend]
    strategy:
      matrix:
        images: [frontend, backend]
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0
      - name: Shorten SHA
        run: echo "SHORT_SHA=${GITHUB_SHA::8}" >> $GITHUB_ENV
      - name: Build Image
        id: build
        run: |
          docker build \
            -t $DOCKER_REPO/fortune-cookies/${{ matrix.images }}:$SHORT_SHA \
            -t $DOCKER_REPO/$GIT_REPO/${{ matrix.images }}:latest \
            ${{ matrix.images }}/
      - name: Push Image
        if: steps.build
        run: docker push --all-tags $DOCKER_REPO/fortune-cookies/${{ matrix.images }}
  
